apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2018-08-20T20:16:36Z
  generation: 1
  labels:
    run: rtsp-client
  name: rtsp-client
  namespace: default
  resourceVersion: "59899"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/rtsp-client
  uid: f09122f7-a4b5-11e8-a2c7-080027b15a4b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: rtsp-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rtsp-client
    spec:
      volumes:
      - name: rtsp-client-data-volume
        persistentVolumeClaim:
          claimName: task-rtsp-client-data-claim
      - name: rtsp-client-logs-volume
        persistentVolumeClaim:
          claimName: task-rtsp-client-logs-claim
      initcontainers:
      - image: busybox
        tag: 0.1
        name: inittest
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/data"
            name: rtsp-client-data-volume
        command: ["/bin/sh"]
        args: ["-c","echo \"192.168.1.5!AA:AA:AA:AA:AA:AA\" > /data/cameras.txt"]
#      - image: busybox
#        tag: 0.1
#        name: init-ping
#        imagePullPolicy: Never
#        command: ["/bin/sh"]
#        args: ["-c","ping -W 5 -c 5 192.168.1.5"]
      containers:
      - image: kepler/rtsp-client:stable
        imagePullPolicy: Never
        name: rtsp-client
        resources: {}
        volumeMounts:
          - mountPath: "/data"
            name: rtsp-client-data-volume
          - mountPath: "/logs"
            name: rtsp-client-logs-volume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
