apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2018-08-20T20:16:36Z
  generation: 1
  labels:
    run: rtsp-client
  name: rtsp-client
  namespace: default
  resourceVersion: "59899"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/rtsp-client
  uid: f09122f7-a4b5-11e8-a2c7-080027b15a4b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: rtsp-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rtsp-client
    spec:
      containers:
          - image: kepler/rtsp-client:stable
        imagePullPolicy: Always
        name: rtsp-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
