version: '3'

services:

  vvms:
      build: volume-manager
      volumes:
        - vm-data:/data
        - vm-logs:/logs

  discovery-service:
      build: discovery-service
      privileged: true
      network_mode: host
      volumes:
        - vm-data:/data
        - vm-logs:/logs
      restart: on-failure
      environment:
       - CIDR="10.50.14.1/22"
       - MAC_ID="00:02:D1"
      entrypoint: ["/bin/true"]

  rtsp-client:
    build: rtsp-client
    restart: always
    depends_on:
      - media-server
    volumes:
      - vm-data:/data
      - vm-logs:/logs
    networks:
      - vms

  media-server:
    build: nginx-vms
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - vm-data:/data
      - vm-logs:/logs
    networks:
      - vms

volumes:
  vm-logs:
  vm-data:

networks:
  vms:

