version: '3'

services:

  rtsp-client-mp4:
      image: jrottenberg/ffmpeg
      restart: on-failure
      command: ["-i", "rtsp://192.168.1.5:8554/unicast", "-y", "-an", "-vcodec", "copy", "-f", "mp4", "/data/rec/vod/stream.mp4"]
      volumes:
          - /tmp/data/rec:/data/rec/
      networks:
        - vms


  media-server:
      build: nginx-vms
      ports:
        - "1935:1935"
        - "8080:8080"
      volumes:
      - /tmp/data:/data
      networks:
        - vms


networks:
  vms:

