version: '3'

services:

  discovery-service:
      build: discovery-service
      privileged: true
      network_mode: host
      volumes:
       - /tmp/data/:/data # Move away from shared share - use volume containers
       - /tmp/logs:/logs
      restart: on-failure


  rtsp-client:
    build: rtsp-client
    restart: always
    depends_on:
      - media-server
    volumes:
       - /tmp/data:/data
       - /tmp/logs:/logs
    networks:
      - vms

  media-server:
    build: nginx-vms
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - /tmp/data:/data
      - /tmp/logs:/logs
    networks:
      - vms

networks:
  vms:

