kind: PersistentVolume
apiVersion: v1
metadata:
  name: rtsp-client-logs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/vms/client/logs"
