kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-rtsp-client-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
